FROM openjdk:17-jdk-alpine

WORKDIR /app

RUN mkdir -p /app/uploads

COPY build/libs/Photo-colorizing-GAN-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar", "--server.port=8082"]