version: '1'

services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile-java
    container_name: java_service
    networks:
      - my_network
    ports:
      - "8082:8082"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: python_service
    networks:
      - my_network
    ports:
      - "5000:5000"

networks:
  my_network:
    driver: bridge
